### ISSUE TITLE
proofreader_ck5' product is not enabled or allowed

### ISSUE THREAD

**Issue by brxshncy** [WebSpellChecker/wproofreader-ckeditor5#22]
Hello I'm currently having this issue, when using cloud free trial version .

{"error":true,"is_critical":0,"message":"'proofreader_ck5' product is not enabled or allowed. Contact support@webspellchecker.net for more details.","command":"get_info"}

My configuration
                wproofreader: {
                                serviceId: 'MY_SERVICE_ID',
                                srcUrl: 'https://svc.webspellchecker.net/spellcheck31/wscbundle/wscbundle.js',
                                autoStartup: true,
                                enableGrammar: true,
                                lang: 'en_US',
                                enableBadgeButton: true,
                                actionItems: ['addWord', 'ignoreAll', 'settings', 'toggle', 'proofreadDialog'],
                                onErrorRequest: function (err) {
                                    console.log('err', err.message)
                                }
                }

**Comment by nadya-bodrova** [comment]
Hello @brxshncy, 

The WProofreader plugin for CKEditor 5 is a separate product, which should be enabled on our side by request. Please contact us at support@webspellchecker.net and provide your activation key, so that we can enable the plugin for your subscription.

Regards,

**Comment by brxshncy** [comment]
Hello I already had the activation key given as a parameter when
configuring the WProofreader plug in,
[image: image.png]
here is my activation key  *0K9LpHdPhb3NktN*

**Comment by nadya-bodrova** [comment]
Thank you for providing your activation key, which helped me to identify your trial subscription. Not it is better to hide the key from this conversation].

I have already enabled the WProofreader plugin for CKEditor 5 to the subscription. It might take up to 5-10 minutes to apply the changes. Please feel free to write back to us at <support@webspellchecker.net> if any further questions arise.

**Comment by brxshncy** [comment]
Thank you for the fast response, problem solved! Great service @nadya-bodrova . :)
