### ISSUE TITLE
Themes are NOOP?

### ISSUE THREAD

**Issue by vitality82** [WebSpellChecker/wproofreader-ckeditor5#33]
I'm trying to set a theme but the spellcheck bubble is always orange. Looking at webspellchecker options it does look like a supported config prop:

```
ClassicEditor.create( element, {
				wproofreader: {
					serviceId: <SERVICE_ID>
					srcUrl: 'https://svc.webspellchecker.net/spellcheck31/wscbundle/wscbundle.js',
					theme: 'gray'
				},
```

**Comment by jshaptala** [comment]
@vitality82, the default theme for CKEditor 5 plugin is 'ckeditor5', it doesn't change style of the badge but it changes the overall look&feel. Also, we offer 'custom' theme that allows overwriting the default CSS styles. Some tips your can find [here](https://docs.webspellchecker.net/pages/viewpage.action?pageId=468844969).
Check here all available [API options for WProofreader core](https://webspellchecker.com/docs/api/wscbundle/Options.html).

**Comment by vitality82** [comment]
Didn't knew about these docs. Thanks!

**Comment by jshaptala** [comment]
You are welcome.

All the docs for WebSpellChecker software can be found [here](https://docs.webspellchecker.net/) and accessed directly from our [corp website](https://webspellchecker.com/) main menu.
