### ISSUE TITLE
Is the part that adds styles and interactions to ckeditor5 open source?

### ISSUE THREAD

**Issue by uniconnector** [WebSpellChecker/wproofreader-ckeditor5#73]
Is the part that adds styles and interactions to ckeditor5 open source?
I am very interested in how to control the style and interaction of ckeditor5 content, but when using rangy to increase interaction, it always conflicts with the events of ckecitor5. I would like to ask what kind of solution is there?

**Comment by jshaptala** [comment]
The WProofreader plugin for CKEditor 5 utilizes proprietary code under the hood to handle interactions with the text and styles.
For insights into how the functionality works and is built, please refer to our Medium article “[Befriending WYSIWYG Editors: Text Highlighting with Virtual Underlines](https://medium.com/beyond-webspellchecker/befriending-wysiwyg-editors-text-highlighting-with-virtual-underlines-48c80a680b2f)”.
