### ISSUE TITLE
Update CKEditor 5 plugin with improved installation methods

### ISSUE THREAD

**Issue by KaterynaVorobei** [WebSpellChecker/wproofreader-ckeditor5#77]
CKEditor's team are improving CKEditor 5 installation methods to simplify the process and enhance the developer experience. Check more information here: https://github.com/ckeditor/ckeditor5/issues/15502

PR is here: https://github.com/WebSpellChecker/wproofreader-ckeditor5/pull/75

Release ETA is around 20.06. Final release date will be confirmed in the following days.

**Comment by Bohdan-Chui** [comment]
A plugin with version [3.0.0](https://www.npmjs.com/package/@webspellchecker/wproofreader-ckeditor5/v/3.0.0) was released.
